apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-builder-images
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fusion-forge.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
data:
  {{- range $key, $value := .Values.builderImages }}
  {{ $key | quote }}: {{ $value | quote }}
  {{- end }}
