{{- if and .Values.postgresql.enabled (not .Values.postgresql.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-postgresql-secret" .Release.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "fusion-forge.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
type: Opaque
stringData:
  username: {{ .Values.postgresql.auth.username | quote }}
  password: {{ .Values.postgresql.auth.password | quote }}
{{- else if and (not .Values.postgresql.enabled) (not .Values.postgresql.external.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-db-secret" .Release.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "fusion-forge.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
type: Opaque
stringData:
  username: {{ .Values.postgresql.external.username | quote }}
  password: {{ .Values.postgresql.external.password | quote }}
{{- end }}
