apiVersion: v1
kind: Service
metadata:
  name: {{ include "fusion-forge.serverServiceName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "fusion-forge.labels" . | nindent 4 }}
    app: fusion-forge-server
    app.kubernetes.io/component: server
spec:
  type: ClusterIP
  selector:
    app: fusion-forge-server
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
